version: '3'
services:
  bengoboxapi:
    container_name: bengoboxapi
    environment:
      - DB_ROOT_PASSWORD=@Bengomall123
      - DB_USER=bengoboxuser
      - DB_PASSWORD=@Bengomall123
      - DB_NAME=bengomall
      - DB_HOST=192.168.8.8
    image: bengoboxapi:latest
    mem_limit: 8000M
    cpus: 2
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - /home/titusdev/projects/Ecommerce/backups:/app/backups
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8001 -w 4 --timeout 120
  # bengoboxui:
  #   container_name: bengoboxui
  #   environment:
  #     - VUE_APP_BASE_URL='http://localhost:8001/api/'
  #   image: bengoboxui:latest
  #   ports:
  #     - "3000:8080"
    # depends_on:
    #   - bengoboxapi
