# Generated by Django 4.2.6 on 2023-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'cart',
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
