# Generated by Django 4.2.6 on 2023-11-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0006_alter_stockinventory_serial_alter_stockinventory_sku'),
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='stock',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='stockinventory.stockinventory'),
            preserve_default=False,
        ),
    ]
