# Generated by Django 4.2.6 on 2023-11-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_product_cart_price_cart_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='retail_price',
        ),
    ]
