# Generated by Django 4.2.6 on 2023-10-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_alter_addressbook_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaddress',
            name='defualt_AddressBook',
        ),
    ]
