# Generated by Django 4.2.6 on 2023-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_remove_businessaddress_defualt_addressbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaddress',
            old_name='region',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='businessaddress',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='box',
            field=models.CharField(default='00100-397', max_length=500),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='street_or_road',
            field=models.CharField(default='Along Kisumu-Busia Road', max_length=255, verbose_name='Street/Road'),
        ),
    ]
