# Generated by Django 4.2.6 on 2023-10-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_rename_region_businessaddress_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='delivery_Address',
        ),
    ]
