# Generated by Django 4.2.6 on 2023-10-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_remove_addressbook_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='addressbook',
            name='last_name',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='address_label',
            field=models.CharField(default='my address 1', max_length=255),
        ),
    ]
