# Generated by Django 4.2.6 on 2023-11-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0006_remove_addressbook_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='defualt_Address',
            new_name='defualt_address',
        ),
    ]
