# Generated by Django 4.2.6 on 2023-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0007_rename_defualt_address_addressbook_defualt_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='postal_code',
            field=models.CharField(blank=True, default='57-40100', max_length=100, null=True),
        ),
    ]
