# Generated by Django 4.2.6 on 2023-11-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0009_alter_addressbook_defualt_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'managed': True, 'verbose_name_plural': 'AddressBook'},
        ),
        migrations.AlterModelOptions(
            name='businessaddress',
            options={'managed': True, 'verbose_name_plural': 'Business Addresses'},
        ),
        migrations.RenameField(
            model_name='addressbook',
            old_name='defualt_address',
            new_name='default_address',
        ),
    ]
