# Generated by Django 4.2.6 on 2023-12-11 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 15, 53, 27, 328554)),
        ),
    ]
