# Generated by Django 4.2.6 on 2023-10-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcolor_productsize_remove_products_variations_and_more'),
        ('stockinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinventory',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor'),
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsize'),
        ),
    ]
