# Generated by Django 4.2.6 on 2023-11-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('stockinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='human_resource.supplier'),
        ),
    ]
