# Generated by Django 4.2.6 on 2023-11-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0003_stockinventory_serial_stockinventory_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinventory',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Re-Order', 'Re-Order')], default='In Stock', max_length=20),
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='is_deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
