# Generated by Django 4.2.6 on 2023-10-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0003_stockinventory_adjusted_dicount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinventory',
            name='adjusted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
