# Generated by Django 4.2.6 on 2023-11-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_products_availability_and_more'),
        ('stockinventory', '0004_stockinventory_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.products'),
        ),
        migrations.AlterField(
            model_name='stockinventory',
            name='usage',
            field=models.CharField(blank=True, choices=[('EX-UK', 'EX-UK'), ('Refurbished', 'Refurbished'), ('Used Like New', 'Used Like New'), ('Secod Hand', 'Second Hand'), ('New', 'New')], default='New', help_text='Leave blank if not applicable', max_length=20, null=True),
        ),
    ]
