# Generated by Django 4.2.6 on 2023-10-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0004_stockinventory_adjusted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='adjusted_dicount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockinventory',
            name='adjusted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
