# Generated by Django 4.2.6 on 2023-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0005_alter_stockinventory_adjusted_dicount_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinventory',
            old_name='adjusted_dicount_price',
            new_name='dicount_price',
        ),
        migrations.RemoveField(
            model_name='stockinventory',
            name='adjusted_price',
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
