# Generated by Django 4.2.6 on 2023-10-31 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0006_rename_adjusted_dicount_price_stockinventory_dicount_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinventory',
            old_name='dicount_price',
            new_name='variation_discount_price',
        ),
        migrations.RenameField(
            model_name='stockinventory',
            old_name='unit_price',
            new_name='variation_price',
        ),
    ]
