# Generated by Django 4.2.6 on 2023-10-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0007_rename_dicount_price_stockinventory_variation_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='variation_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
