# Generated by Django 4.2.6 on 2023-11-11 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinventory',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 10, 12, 54, 269065)),
        ),
    ]
