# Generated by Django 4.2.6 on 2023-11-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0008_alter_stockinventory_variation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='variation_discount_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stockinventory',
            name='variation_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
