# Generated by Django 4.2.6 on 2023-11-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0009_alter_stockinventory_variation_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinventory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stockinventory',
            name='variation_discount_price',
        ),
        migrations.RemoveField(
            model_name='stockinventory',
            name='variation_price',
        ),
    ]
