# Generated by Django 4.2.6 on 2023-11-11 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0009_remove_stockinventory_flash_sale_end_date_frontstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontstore',
            options={'verbose_name': 'Front Store Settings', 'verbose_name_plural': 'Front Store Settings'},
        ),
        migrations.AddField(
            model_name='frontstore',
            name='slider_image',
            field=models.FileField(blank=True, null=True, upload_to='store/slider'),
        ),
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 10, 27, 8, 634979)),
        ),
    ]
