# Generated by Django 4.2.6 on 2023-11-11 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0010_alter_frontstore_options_frontstore_slider_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontstore',
            name='slider_image',
        ),
        migrations.AddField(
            model_name='stockinventory',
            name='slider_image',
            field=models.FileField(blank=True, null=True, upload_to='store/slider'),
        ),
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 10, 28, 25, 281387)),
        ),
    ]
