# Generated by Django 4.2.6 on 2023-11-11 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0011_remove_frontstore_slider_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontstore',
            name='slider_text',
            field=models.CharField(default='Upto 60% + Extra 10%', max_length=100),
        ),
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 10, 47, 17, 160970)),
        ),
    ]
