# Generated by Django 4.2.6 on 2023-11-13 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0012_frontstore_slider_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 10, 45, 20, 911379)),
        ),
    ]
