# Generated by Django 4.2.6 on 2023-11-13 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0016_alter_frontstore_flash_sale_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 20, 20, 35, 690994)),
        ),
    ]
