# Generated by Django 4.2.6 on 2023-11-19 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_unit_unit_symbol'),
        ('stockinventory', '0018_alter_frontstore_flash_sale_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 15, 40, 36, 158709)),
        ),
        migrations.AlterField(
            model_name='stockinventory',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsize', verbose_name='Packaging'),
        ),
    ]
