# Generated by Django 4.2.6 on 2023-11-21 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0019_alter_frontstore_flash_sale_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 15, 35, 59, 757033)),
        ),
    ]
