# Generated by Django 4.2.6 on 2023-11-21 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0020_alter_frontstore_flash_sale_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 15, 50, 8, 529684)),
        ),
    ]
