# Generated by Django 4.2.6 on 2023-12-09 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0021_alter_frontstore_flash_sale_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 22, 16, 24, 385915)),
        ),
    ]
