# Generated by Django 4.2.6 on 2023-11-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
