# Generated by Django 4.2.6 on 2023-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='sku',
            field=models.CharField(default='103', max_length=100),
        ),
        migrations.DeleteModel(
            name='SpecialOffers',
        ),
    ]
