# Generated by Django 4.2.6 on 2023-11-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_salesitems_sku_delete_specialoffers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='product',
        ),
    ]
