# Generated by Django 4.2.6 on 2023-11-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockinventory', '0007_review'),
        ('pos', '0004_remove_salesitems_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='sku',
        ),
        migrations.AddField(
            model_name='salesitems',
            name='stock',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='salesitems', to='stockinventory.stockinventory'),
            preserve_default=False,
        ),
    ]
