# Generated by Django 4.2.6 on 2023-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_salesitems_sku_salesitems_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
