# Generated by Django 4.2.6 on 2023-11-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], default='withdrawal', max_length=20),
        ),
    ]
