# Generated by Django 4.2.6 on 2023-11-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_transaction_transactiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitems',
            old_name='price',
            new_name='retail_price',
        ),
    ]
