# Generated by Django 4.2.6 on 2023-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_rename_price_salesitems_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_type',
            field=models.CharField(choices=[('walk-in', 'walk-in customer'), ('online', 'online customer')], default='walk-in customer', max_length=20),
        ),
    ]
