# Generated by Django 4.2.6 on 2023-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_sales_sales_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='paymethod',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'Mpesa'), ('mpesa_on_delivery', 'Mpesa on Delivery')], default='cash', max_length=20, null=True),
        ),
    ]
