# Generated by Django 4.2.6 on 2023-10-11 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='category/display')),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='maincategory/display')),
                ('status', models.IntegerField(default=1)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
                'db_table': 'main_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/%Y%m%d/')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
                'db_table': 'productimages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(max_length=100)),
                ('serial', models.CharField(default='0671860013525', max_length=255)),
                ('title', models.TextField(default='Hp x2 1033', max_length=500)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('dimentions', models.CharField(blank=True, default='1x2x3', max_length=50, null=True)),
                ('availability', models.CharField(default='In Stock', max_length=20)),
                ('categories', models.ManyToManyField(to='product.category')),
                ('images', models.ManyToManyField(related_name='products', to='product.productimages')),
                ('maincategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.maincategory')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='category/subcategory/display')),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'subcategories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='color', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='blue', max_length=255, null=True)),
                ('count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Product Variations',
                'db_table': 'product_variations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='product.variations'),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor'),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='product.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourites',
                'verbose_name_plural': 'Favourites',
                'db_table': 'savedproducts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='Subcategories',
            field=models.ManyToManyField(blank=True, null=True, to='product.subcategory'),
        ),
    ]
