# Generated by Django 4.2.6 on 2023-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(default='500', max_length=10),
        ),
    ]
