# Generated by Django 4.2.6 on 2023-11-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productsize_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='unit_dicount_price',
            new_name='unit_discount_price',
        ),
    ]
