# Generated by Django 4.2.6 on 2023-10-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_unit_alter_productsize_size_productsize_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, help_text='Enter unit price(e.g 0.12*500=60)', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, help_text='Enter unit price(e.g 0.12*500=60)'),
        ),
    ]
