# Generated by Django 4.2.6 on 2023-10-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_discount_price_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subcategories',
        ),
    ]
