# Generated by Django 4.2.6 on 2023-10-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_products_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, help_text='Enter unit price(e.g 0.12*500=60)', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, help_text='Enter unit price(e.g 0.12*500=60)'),
        ),
    ]
