# Generated by Django 4.2.6 on 2023-11-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_unit_options_rename_name_unit_unit_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='products',
            name='usage',
        ),
    ]
