# Generated by Django 4.2.6 on 2023-11-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_products_serial_remove_products_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_deal_of_the_day',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_flash_sale',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_new_arrival',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_top_pick',
        ),
    ]
