# Generated by Django 4.2.6 on 2023-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='retail_price',
        ),
        migrations.AddField(
            model_name='products',
            name='unit_price',
            field=models.FloatField(default=0, help_text='Enter general price or leave it as 0.0 and set unit price in variations'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='retail_price',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
