# Generated by Django 4.2.6 on 2023-11-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_remove_products_images_productimages_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Color Variation', 'verbose_name_plural': 'Color Variation'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'managed': True, 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Size Variation', 'verbose_name_plural': 'Size Variation'},
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.products'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Re-Order', 'Re-Order')], default='In Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, help_text='Enter general discount price or leave it as 0.0 and set unit price in variations', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, help_text='Enter general price or leave it as 0.0 and set unit price in variations'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
