# Generated by Django 4.2.6 on 2023-11-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productcolor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='usage',
            field=models.CharField(blank=True, choices=[('EX-UK', 'EX-UK'), ('Refurbished', 'Refurbished'), ('New', 'New')], default='New', help_text='Leave blank if not applicable', max_length=20, null=True),
        ),
    ]
