# Generated by Django 4.2.6 on 2023-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_price_products_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_symbol',
            field=models.CharField(max_length=50),
        ),
    ]
