# Generated by Django 4.2.6 on 2023-10-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='confirmed_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
