# Generated by Django 4.2.6 on 2023-11-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_product_orderitem_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery_address',
        ),
    ]
