# Generated by Django 4.2.6 on 2023-11-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('stockinventory', '0007_review'),
        ('order', '0003_rename_address_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sku',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='stockinventory.stockinventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.pickupstations'),
        ),
    ]
