# Generated by Django 4.2.6 on 2023-11-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('order', '0004_remove_orderitem_product_sku_orderitem_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='human_resource.pickupstations'),
        ),
    ]
