# Generated by Django 4.2.6 on 2023-11-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='retail_price',
        ),
    ]
